### ISSUE TITLE
Running dsc-node on a Pi 3

### ISSUE THREAD

**Issue by rjemanuele** [denvera/dsc-node#3]
I'm getting a SyntaxError trying to use dsc-node with a new Pi.  Any thoughts?

Thanks!

```
rje@starman:~/dsc-node $ npm start

> dsc-node@0.0.3 start /home/rje/dsc-node
> node app.js

/home/rje/dsc-node/node_modules/nodemailer/lib/mailer/index.js:31
            compile: [(...args) => this._convertDataImages(...args)],
                       ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/rje/dsc-node/node_modules/nodemailer/lib/nodemailer.js:3:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! dsc-node@0.0.3 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dsc-node@0.0.3 start script.
npm ERR! This is most likely a problem with the dsc-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls dsc-node
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.59-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/rje/dsc-node
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/rje/dsc-node/npm-debug.log
npm ERR! not ok code 0
rje@starman:~/dsc-node $
```

**Comment by sj-louw** [comment]
@rjemanuele It seems like you are using node version 4.8.2. You can try upgrading to node version 6.x and run `npm install` again. I am using node version 6.9.5 and all seems good.

**Comment by rjemanuele** [comment]
Thank you @sj-louw upgrading node to v9.5.0 got me much further.  Now after creating a "log" directory and connecting to the the sever created by 'npm start' the web browser is still blank but something loads and a few files return 404.


```
rje@starman:~/dsc-node $ npm start

> dsc-node@0.0.3 start /home/rje/dsc-node
> node app.js

{"name":"dscserver","hostname":"starman","pid":5018,"level":20,"msg":"Added job Stay every night with spec 0 0 1 * * * to stay","time":"2018-02-09T07:30:53.024Z","v":0}
{"name":"dscserver","hostname":"starman","pid":5018,"level":20,"msg":"Added job Disarm for the Thandi with spec 0 30 7 * * 3 to disarm","time":"2018-02-09T07:30:53.038Z","v":0}
Server started
Listening on port 3333
GET /app.css 404 15.978 ms - 146
GET /javascripts/vendor.js 404 15.113 ms - 160
GET /javascripts/app.js 404 15.484 ms - 157
GET /javascripts/vendor.js 404 3.020 ms - 160
```

**Comment by sj-louw** [comment]
@rjemanuele In `config/default.json`, Change `"mode":"socket"` to `"mode":"dev"`. With the Linux kernel module installed the frontend must be able to talk to the "dev" device, not socket. Furthermore I had to do `brunch build` before the server started successfully.

**Comment by denvera** [comment]
Hi @rjemanuele, thanks for checking out the project!

You might need to do a `bower install` and `brunch build` if I remember correctly to generate the assets and move them to the correct place before running the server.

**Comment by rjemanuele** [comment]
Hi @denvera this looks like a really neat project and I built a Pi shield to hook it to my system.  I've gotten dscmod working and this is my last step.  `bower install` seemed to work ok.  `brunch build` is getting a few errors.

```
rje@starman:~/dsc-node $ ./node_modules/brunch/bin/brunch build
{"name":"dscserver","hostname":"starman","pid":26621,"level":20,"msg":"Added job Stay every night with spec 0 0 1 * * * to stay","time":"2018-02-09T18:39:53.240Z","v":0}
{"name":"dscserver","hostname":"starman","pid":26621,"level":20,"msg":"Added job Disarm for the Thandi with spec 0 30 7 * * 3 to disarm","time":"2018-02-09T18:39:53.255Z","v":0}
Server started
18:39:53 - warn: You have declared express in package.json more than once
18:39:58 - info: compiling
18:39:59 - error: Compiling of node_modules/jade/runtime.js failed. Error: Couldn't find preset "/home/rje/dsc-node/node_modules/babel-preset-latest" relative to directory "node_modules/jade"
Stack trace was suppressed. Run with `LOGGY_STACKS=1` to see the trace.
18:39:59 - error: Compiling of app/application.js failed. Error: Couldn't find preset "/home/rje/dsc-node/node_modules/babel-preset-latest" relative to directory "app"
Stack trace was suppressed. Run with `LOGGY_STACKS=1` to see the trace.
18:39:59 - error: Compiling of app/components.jsx failed. Error: Couldn't find preset "/home/rje/dsc-node/node_modules/babel-preset-latest" relative to directory "app"
Stack trace was suppressed. Run with `LOGGY_STACKS=1` to see the trace.
18:39:59 - warn: app/styles/main.scss compiled, but not written. Check your stylesheets.joinTo config
rje@starman:~/dsc-node $
```

**Comment by rjemanuele** [comment]
@denvera  Ok, so I was missing `babel-preset-latest`.  It is running now and presents me with a keypad.

I don't see any messages under KeyBus Messages nor do I see any Leds lit for Program or Ready when appropriate.

Messages are definately coming in on /dev/dsc_txt.  I have tried running `sudo npm start`.

**Comment by rjemanuele** [comment]
So I needed to set mode to `dev` in the default.json to get it working.  So far so good.  Keypad works.
